### ISSUE TITLE
Forum displaying error message on first connect

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#124]
I've been seeing the following lately when I first open the forums: 
![image](https://user-images.githubusercontent.com/7004392/34913083-f7fdb6f4-f8b8-11e7-9048-b7217f860415.png)

Reloading the page clears it and shows the forums as normal, but this could be an early indication of instability.

**Comment by tlackemann** [comment]
Make sure you're not connecting directly after waking your computer up.

The support forums use [Discourse](https://www.discourse.org/) and they use WebWorkers to keep the site online even when your offline. If your computer is waking up and not yet connected (happens to my Macbook all the time) you'll be greeted with this lovely connection error.

I don't think it's actually a bug but rather a circumstance of using Discourse in a semi-offline state.

Feel free to keep open if you disagree but otherwise I think this can be closed.

**Comment by Aquaricat** [comment]
Except that I never put my PC to sleep - I've seen this happen multiple times in the same browser session, though several hours apart.  But good to know about the WebWorkers thing - I was guessing it was some sort of strange caching.  Closing!
