### ISSUE TITLE
Ability to make hidden rolls in macros. !hidden/!hroll

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#166]
Currently, any time `!roll` is called, it sends the output to the chat history.  While this makes sense, it means that some macros will result in an excessive amount of chat scroll, only to repeat the results via various `!say` or `!template` calls.  What's needed is the ability to make hidden rolls, which aren't sent to the chat but are available within the macro for later use.

```
!hidden {roll formula} + @me.dexterity_mod + @me.proficiency_bonus >> $atk1 = $1
!hroll {roll forumla} >> $atk2 = $2
!target "Select target."
!say "Atk: ${atk1} | ${atk2} vs. @{target}.name's AC (@{target}.ac)"
```
Note that this also necessitates the inclusion of #110 to avert the possibility of less honest players from simply supplying the result they want, rather than performing a roll.

**Comment by Pjb518** [comment]
To be clear, because I think this suggestion has been misrepresented in the Discord chat, this is to prevent chat clutter _for everyone_, including the player making the rolls and the GM. The rolls and the eventual output are very different things and we need a way to do the former without the latter.

The suggested `!hroll` `!hr!` (hidden) and `broll` `br` (blind) from the Discord server are completely different. The `!hroll` from the Discord server is a means of sending a roll as a whisper, while `!broll` is a means of sending a roll to the GM without the player knowing what the result is. Both of these are useful, but ultimately different things from what are being suggested here.

**Comment by Pjb518** [comment]
Regarding the `!hroll` from the Discord server, I think we should implement that as `!wroll` and `!wr` (whispered roll). It will take a target, just like whisper, giving us this format:

`!wr @target 2d20kh1 + 5 "Comments"`

**Comment by Pjb518** [comment]
After some discussion with @Aquaricat , I think we're keen on:

```bash
!hide-roll    !hr
!whisper-roll    !wr
!blind-roll    !br
```

Hide roll is what we've been talking about. Keeping a roll from going to the chat so you can ram it in a variable and use it elsewhere.

Whisper roll is for sending a roll to one or more people but keeping it out of general chat. Should accept GM and DM as aliases.

Blind roll is for sending a roll to the GM that you, as the sender, do not get to see. This is useful for all manner of games, and situations, where the player should not know if they succeeded.

**Comment by Aquaricat** [comment]
The first round of support for this has been added, with the syntax 
```
!hroll {roll formula}
!wroll {target} {roll formula}
```
Leaving this issue open for a bit, as it's still very early in the implementation.

**Comment by Pjb518** [comment]
I haven't had any issues recently, and the new shorthand `!hr` and `!wr` are working as expected. I'm going to close this and we can open new tickets for specific errors and proposals.
