### ISSUE TITLE
Merge proficiency boxes?

### ISSUE THREAD

**Issue by khionu** [UnicornHeartClub/Issues#180]
I honestly can't see a reason they're split. Additionally, I feel it's counter intuitive to have Tools separate from Weapons/Armour. There's also not much separating them that is specific to our mechanics.

So, could/should we merge them?

**Comment by Aquaricat** [comment]
Traditionally, Tools are separate in VTT platforms because they represent rolls, while things like weapons, armor, and language proficiency are strictly informational.  

You don't need to roll your heavy armor proficiency, it's just a boolean "yes, you can use heavy armor", thus the record doesn't need to include the cruft of modifiers and bonuses and this, that and the other thing.  

However, you *do* need to be able to roll your smithing tools to repair your heavy armor, with considerations such as expertise, bonuses, and modifier to use.

**Comment by khionu** [comment]
I see.... well, I personally don't feel that that necessitates separation, but I can see how others might. If it comes down to just that preference, I would like us to re-evaluate whether it's worth the UX distinction.

**Comment by Aquaricat** [comment]
IMHO, it should stay separate, because the goals are explicitly different:

#### Example: Smith's Tools with Proficiency  
In this case, the character has proficiency with Smith's Tools.  Recording this "correctly" means entering the proficiency in the Proficiency section (Soandso has proficiency with Smithing Tools), and then configuring the parameters of the roll. (Soandso attempts to use Smithing Tools, and rolls `1d20 [Base] + @{me}.proficiency_bonus [Proficiency] + @{me}.strength_bonus [Modifier]`).

Here... sure, you could jam all of that together into the Proficiency definition, but that means that now, every entry under Proficiency has to record everything necessary in each entry.  Any armor type, language, weapon type you use - all of them are going to have stubs for proficiency, mod, and bonus that will never, ever be used (short of some sort of homebrew edgecase).  It muddies the information that Proficiency is meant to convey: Soandso can use *x* without penalty.

#### Example: Jeweler's Tools *without* Proficiency  
In this case, the character does *not* have proficiency with Jeweler's Tools - they just have a set.  Maybe it's just for flavor, or maybe the tools they have grant some sort of special bonus, separate of proficiency.  Recording this "correctly" means NOT entering the tools as a Proficiency (Soandso doesn't have proficiency with Jeweler's Tools), but still configuring the parameters of the roll. (Soandso attempts to use Jeweler's Tools, and rolls `1d20 [Base] + @{me}.dexterity_bonus [Modifier] + 1 [Special Bonus]`).  

This clearly illustrates the division of purpose of the section - just because a character is using a tool doesn't mean that they are proficient with them.  If you record the custom roll as part of proficiency, it implies that the character has that proficiency, when that is explicitly false.  On the other hand, by keeping them separate, you can still record the correct information and make the roll.  

#### Example: Custom Arbitrary Rolls  
Here, the character has a racial ability that grants them a special bonus on hearing-based perception checks.  There are a couple ways this could be done - you could write a special macro, enter the roll manually with a `!roll` command... or you could take advantage of the flexibility in the Tools section, and add it there, where it's highly visible and easy to click.  

It avoids duplicating information - the fact that the character has proficiency with Perception (or not) is already recorded in the Skills section.  It also simplifies the task for less savvy users that don't want to bother with making a macro, and places the ability in easy view on the core of the sheet so that it's not forgotten on the macro page.  

In this case, sure, we're stretching the intended purpose of the Tools section a little, but I'd argue that it'd make more sense to rename the section to "Tools/Custom Rolls" in any case.  If we were to combine Tools and Proficiencies, though, now we're discussing lines that have nothing to do with proficiency at all mixed in with just information (Weapon/Armor) and traditional tools (Smith's, Jeweler's).

**Comment by Aquaricat** [comment]
Closed per go-ahead from @khionu via Discord. 
![image](https://user-images.githubusercontent.com/7004392/36443089-645f1e5e-163d-11e8-8281-cc7189dccab8.png)
