### ISSUE TITLE
Currency on SRD Sheets

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#55]
There currently is no place to add money on an SRD sheet. We should add boxes for the standard currency values on the sheet (copper, silver, electrum, gold, and platinum). This would be much neater than keeping a value in the treasure section among other loot.

Adding currency as elements on the sheet would also allow us to make them attributes, which would enable DMs to automatically distribute loot to their players with macros and triggers if they desired.

**Comment by Aquaricat** [comment]
Currency as handled in 5e is painful.  This is an area where a little magic baked into the sheet could go a long way to helping PVTT stand out.  Some possible bonus functionality:
* I as a player would **love** to be able to just type in an amount like `+150g -23s -1032c` and have the sheet handle adding/subtracting that automatically and smartly.  If I don't have 1032 copper, the sheet should be smart enough to subtract 11g and convert intelligently into silver and copper.  Currency management is a PAIN!!!
* Allow for custom forms of currency tracking.  Some DMs are going to use thematic special currencies like shells, for example.

**Comment by tlackemann** [comment]
This seems like a great setup for a 5e macro ;) I don't think the language could support +150g etc only because that becomes really specific to 5e currency management.

The sheet however _is_ missing currency information so I am going to add that. You will be able to configure each attribute via a macro attribute so I imagine being able to write a `!input` command asking you to input your amount and you can handle it appropriately (more so after switch statements are in)

**Comment by Pjb518** [comment]
Sheet currency is functioning as expected, and modifying them via attributes also works.

Handling things like loot and currency can definitely be done using macros, so we'll add this to the list for useful macros we need to write up.
