### ISSUE TITLE
Unable to assign more than one ${var} after !target.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#87]
```
!roll 1d20 + @me.proficiency_bonus + @me.dexterity_mod + 2 >> ${atk1} = ${1}
!roll 1d20 + @me.proficiency_bonus + @me.dexterity_mod + 2 >> ${atk2} = ${2}
!roll 1d8 + @me.dexterity_mod >> ${dmg1} = ${3}
!target "Select target."
${tName} = @target.name
${tAC} = @target.ac
$atk1 > ${tAC} ? !say "Hit " ${tName} " for " ${dmg1} " points of slashing damage." :|
```
So here's an odd one.  With the macro above, I'm working on building a simple attack and damage macro.  As part of that, I try to pull both the target name, and target AC out from the `@target.*` object, and store them in `$vars` since I can't just read them directly in the `!say` statement.  This seems to work ok when I'm pulling just one attribute, but as soon as I try pulling two, the macro fails to work.  The behavior is very consistent - using
```
!target "Select target."
${tName} = @target.name
!say ${tName}
```
invariably works, even if I replace `@target.name` with `@target.ac` or some other attribute.  However, the moment I try
```
!target "Select target."
${tName} = @target.name
${tAc} = @target.ac
!say ${tName} " " ${tAc}
```
it fails, without even asking me to select a target.  Additionally, 
```
!target "Select target."
${tName} = @target.name
${tAc} = 18
!say ${tName} " " ${tAc}
```
**also** fails, suggesting that something about `!target` is breaking the `$var` assignment in general after it's used.
```
${tName} = "Test"
${tAc} = 18
!say ${tName} ${tAc}
```
*does* work as expected.

**Comment by tlackemann** [comment]
This is due to how variables are assigned in steps. It's not ideal but try adding a pipe to the end of your assignment `|`

It's not `!target` that's breaking assignment, it's the dual assignment. Consider this failing example:

```bash
${tXp} = 2400
${tAc} = 18
```

And the equivalent passing example:

```bash
${tXp} = 2400 |
${tAc} = 18
```
The last example you provide _does_ work because it's parsing a quoted string. At the end of the string it gives up parsing and moves onto the next operation. With other assignments that are not strings, there are slightly more complex rules with peeking ahead and parsing, thus the unexpected behavior you're observing. The pipe (`|`) operator should be used in between assignments almost always.

**Comment by Aquaricat** [comment]
Ok, so that's an answer (thank you! ^^), but it's also confusing/inconsistent behavior since it works as (mistakenly) expected for quoted strings.

This is something I foresee coming up often as more folks start writing macros, so should probably update the wiki to clearly indicate that the line terminator (pipe) is required between assignments.  Just out of curiosity - why doesn't the line break constitute a hard break between steps?

**Comment by tlackemann** [comment]
It should but the right now the parser sees almost everything on one line.

That could change in the very near future when I support parsing a JSON object for the template command.

**Comment by Aquaricat** [comment]
Ok.  ^^
